"""Research Edge Lab entry point.

Exports the research API contracts and service boundaries.
Importing this package has no side-effects (no disk writes, network calls,
live trading state access, or heavy model execution).
"""

from __future__ import annotations

# Core data services
from app.services.research.data import (
    CanonicalOHLCVSSchema,
    PreparedDataset,
    enrich_dataset,
    prepare_research_dataset,
    validate_dataset,
)

# Feature extraction
from app.services.research.features import (
    active_sessions_for_hour,
    adr,
    atr,
    atr_percent,
    bb_percent_b,
    bb_width,
    bollinger_bands,
    build_market_regime_feature_frame,
    calculate_regime_features,
    detect_market_regime,
    detect_trend_regime,
    detect_volatility_regime,
    donchian_channel,
    forward_max_adverse_excursion,
    forward_max_favorable_excursion,
    forward_returns,
    hurst_exponent,
    log_returns,
    momentum,
    percent_rank,
    pivot_points,
    rate_of_change,
    rolling_hurst,
    rolling_percentile_rank,
    rsi,
    session_label_for_hour,
    simple_returns,
    zscore,
)

# Helpers
from app.services.research.helpers import (
    calculate_adr,
    calculate_atr,
    calculate_correlation_matrix,
    calculate_returns,
    calculate_seasonality_statistics,
    calculate_session_statistics,
    calculate_spread_statistics,
    calculate_volatility,
    calmar_ratio,
    check_sample_size,
    create_news_blackout_windows,
    expectancy,
    max_drawdown,
    median_mae_mfe,
    parse_calendar_events,
    parse_sentiment_snapshot,
    profit_factor,
    run_session_breakout_strategy,
    run_session_fade_strategy,
    sharpe_ratio,
    sortino_ratio,
    win_rate,
)

# Data leakage detection
from app.services.research.leakage import (
    dump_masked_research_json,
    enforce_time_split,
    mask_forward_columns,
    mask_research_artifact,
    validate_no_lookahead_features,
)

# Core metrics calculator
from app.services.research.metrics import (
    CandlesCalculator,
    MetricCalculator,
    MetricRegistry,
    RangesCalculator,
    ReturnsCalculator,
    RocCalculator,
    SpreadCalculator,
    VolatilityCalculator,
    VolumeActivityCalculator,
    build_default_registry,
)

# Reporting
from app.services.research.reporting import (
    build_dashboard_summary,
    build_edge_lab_scorecard_report,
    build_edge_profile_snapshot,
    build_profile_summary,
    generate_multi_symbol_report,
    result_to_markdown,
    result_to_summary,
    save_json,
    save_json_report,
    save_markdown,
    save_markdown_report,
)

# Studies & Null Models
from app.services.research.studies.eds import (
    run_eds_mean_reversion,
    run_eds_null_baseline,
    run_eds_trend_persistence,
)
from app.services.research.studies.null_models import (
    benjamini_hochberg,
    block_bootstrap_ci,
    block_bootstrap_distribution,
    compare_to_null,
    compute_null_percentile,
    get_acceptance_criteria,
    holm_bonferroni,
    null_distribution_stats,
    permutation_test,
    r_space_null,
    random_entry_null,
    session_randomized_null,
    shuffle_returns_null,
)
from app.services.research.studies.structure import (
    ClassificationResult,
    MarketStructureCalibrationCandidate,
    MarketStructureMetricCalibrationCandidate,
    MarketStructureProfile,
    TrendLeg,
    TrendScoreRow,
    TrendSwingPoint,
    build_calibration_grid,
    build_market_structure_stability_report,
    build_metric_calibration_grid,
    build_research_evidence_pack,
    build_strategy_fit,
    build_validation_summary,
    classify_with_candidate,
    confidence_bucket,
    detect_swing_points,
    evaluate_calibration_candidates,
    evaluate_metric_calibration_candidates,
    evaluate_profile_calibration,
    generate_research_hypothesis,
    label_realized_market_behavior,
    parse_news_items,
    resolve_market_structure_profile,
    resolve_market_structure_profile_overrides,
    symbol_class,
    timeframe_bucket,
)
from app.services.research.studies.unsupervised import (
    UnsupervisedResearchRequest,
    UnsupervisedResearchResult,
    adapt_signals_by_cluster,
    analyze_cluster_outperformance,
    attach_cluster_labels,
    build_unsupervised_insight_report,
    cluster_feature_space,
    compute_forward_returns,
    identify_pca_risk_factors,
    run_pca,
)

# Import config types from settings.py
from app.utils.settings import (
    BootstrapConfig,
    CleaningConfig,
    DataConfig,
    EdgeLabConfig,
    EdgeResult,
    EdgeStats,
    MarketStructureConfig,
    MeanReversionConfig,
    NullModelsConfig,
    PermutationConfig,
    SessionConfig,
    SessionEdgeConfig,
    TradeSample,
    TrendPersistenceConfig,
    create_config,
    research_modeling_module,
)

__all__ = [
    # Settings & Configs
    "BootstrapConfig",
    "CandlesCalculator",
    # Data
    "CanonicalOHLCVSSchema",
    "ClassificationResult",
    "CleaningConfig",
    "DataConfig",
    "EdgeLabConfig",
    "EdgeResult",
    "EdgeStats",
    "MarketStructureCalibrationCandidate",
    "MarketStructureConfig",
    "MarketStructureMetricCalibrationCandidate",
    "MarketStructureProfile",
    "MeanReversionConfig",
    # Metrics
    "MetricCalculator",
    "MetricRegistry",
    "NullModelsConfig",
    "PermutationConfig",
    "PreparedDataset",
    "RangesCalculator",
    "ReturnsCalculator",
    "RocCalculator",
    "SessionConfig",
    "SessionEdgeConfig",
    "SpreadCalculator",
    "TradeSample",
    "TrendLeg",
    "TrendPersistenceConfig",
    "TrendScoreRow",
    "TrendSwingPoint",
    # Unsupervised
    "UnsupervisedResearchRequest",
    "UnsupervisedResearchResult",
    "VolatilityCalculator",
    "VolumeActivityCalculator",
    "active_sessions_for_hour",
    "adapt_signals_by_cluster",
    "adr",
    "analyze_cluster_outperformance",
    "atr",
    "atr_percent",
    "attach_cluster_labels",
    "bb_percent_b",
    "bb_width",
    "benjamini_hochberg",
    "block_bootstrap_ci",
    "block_bootstrap_distribution",
    "bollinger_bands",
    # Structure
    "build_calibration_grid",
    "build_dashboard_summary",
    "build_default_registry",
    "build_edge_lab_scorecard_report",
    "build_edge_profile_snapshot",
    "build_market_regime_feature_frame",
    "build_market_structure_stability_report",
    "build_metric_calibration_grid",
    "build_profile_summary",
    "build_research_evidence_pack",
    "build_strategy_fit",
    "build_unsupervised_insight_report",
    "build_validation_summary",
    "calculate_adr",
    "calculate_atr",
    "calculate_correlation_matrix",
    "calculate_regime_features",
    "calculate_returns",
    "calculate_seasonality_statistics",
    "calculate_session_statistics",
    "calculate_spread_statistics",
    "calculate_volatility",
    "calmar_ratio",
    "check_sample_size",
    "classify_with_candidate",
    "cluster_feature_space",
    "compare_to_null",
    "compute_forward_returns",
    # Null Models
    "compute_null_percentile",
    "confidence_bucket",
    "create_config",
    "create_news_blackout_windows",
    "detect_market_regime",
    "detect_swing_points",
    "detect_trend_regime",
    "detect_volatility_regime",
    "donchian_channel",
    "dump_masked_research_json",
    "enforce_time_split",
    "enrich_dataset",
    "evaluate_calibration_candidates",
    "evaluate_metric_calibration_candidates",
    "evaluate_profile_calibration",
    "expectancy",
    "forward_max_adverse_excursion",
    "forward_max_favorable_excursion",
    "forward_returns",
    "generate_multi_symbol_report",
    "generate_research_hypothesis",
    "get_acceptance_criteria",
    "holm_bonferroni",
    "hurst_exponent",
    "identify_pca_risk_factors",
    "label_realized_market_behavior",
    # Features
    "log_returns",
    "mask_forward_columns",
    "mask_research_artifact",
    "max_drawdown",
    "median_mae_mfe",
    "momentum",
    "null_distribution_stats",
    # Helpers
    "parse_calendar_events",
    "parse_news_items",
    "parse_sentiment_snapshot",
    "percent_rank",
    "permutation_test",
    "pivot_points",
    "prepare_research_dataset",
    "profit_factor",
    "r_space_null",
    "random_entry_null",
    "rate_of_change",
    "research_modeling_module",
    "resolve_market_structure_profile",
    "resolve_market_structure_profile_overrides",
    "result_to_markdown",
    "result_to_summary",
    "rolling_hurst",
    "rolling_percentile_rank",
    "rsi",
    "run_eds_mean_reversion",
    # EDS
    "run_eds_null_baseline",
    "run_eds_trend_persistence",
    "run_pca",
    "run_session_breakout_strategy",
    "run_session_fade_strategy",
    "save_json",
    "save_json_report",
    # Reporting
    "save_markdown",
    "save_markdown_report",
    "session_label_for_hour",
    "session_randomized_null",
    "sharpe_ratio",
    "shuffle_returns_null",
    "simple_returns",
    "sortino_ratio",
    "symbol_class",
    "timeframe_bucket",
    "validate_dataset",
    # Leakage
    "validate_no_lookahead_features",
    "win_rate",
    "zscore",
]
