"""Simulation contracts module.

Defines BacktestConfig and BacktestResult.
"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from app.contracts.base import Contract


class BacktestConfig(Contract):
    """Configuration constraints for running a simulator backtest."""

    dataset_refs: list[str] = Field(
        default_factory=list,
        description="References to historical datasets used.",
    )
    strategy_refs: list[str] = Field(
        default_factory=list,
        description="References to strategy models and configs tested.",
    )
    cost_model: str = Field(
        ..., description="Cost model rules mapping (e.g. standard_commission)."
    )
    fill_model: str = Field(
        ..., description="Order execution fill model style (e.g. bar_close)."
    )
    calendar: str = Field(..., description="Session calendar identifier.")
    split_policy: str = Field(
        ..., description="Data splits validation model (e.g. train_test_split)."
    )
    reproducibility_seed: int | None = Field(
        default=None, description="Random seed value for deterministic runs."
    )


class BacktestResult(Contract):
    """The canonical outcomes generated by a simulator run."""

    run_id: str = Field(..., description="Unique backtest Run ID.")
    config_hash: str = Field(
        ..., description="SHA256 fingerprint hash of BacktestConfig."
    )
    journal_ref: str = Field(
        ..., description="Reference link/URI to Persisted ExecutionJournal."
    )
    equity_curve_ref: str = Field(
        ..., description="Reference link/URI to computed equity curve dataset."
    )
    metrics_ref: str = Field(
        ..., description="Reference link/URI to analytics metrics summary."
    )
    evidence_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Evidence validation files and checksums metadata.",
    )
