"""Public registry for the utilities domain.

This module exports approved public names only. It is import-safe and
side-effect free, meaning importing this package does not configure logging,
read configuration files, open network connections, or import heavy optional
dependencies.
"""

from tools.utils.errors import (
    APPROVED_ERROR_CODES,
    ConfigurationError,
    DataError,
    Error,
    ErrorPayload,
    ExternalServiceError,
    SecurityError,
    ValidationError,
    code_for_exception,
    details_for_exception,
    error_name,
    exception_to_error_payload,
    message_for,
    normalize_error_code,
    raise_for_invalid_code,
    validate_error_payload,
)
from tools.utils.identity import (
    DEFAULT_VERSION,
    ID_PREFIXES,
    ensure_version,
    generate_causation_id,
    generate_correlation_id,
    generate_event_id,
    generate_id,
    generate_idempotency_id,
    generate_prefixed_id,
    generate_request_id,
    generate_workflow_id,
    validate_id,
    validate_request_id,
    validate_workflow_id,
)
from tools.utils.logger import (
    clear_trace_context,
    configure_logging,
    get_logger,
    logger,
    set_trace_context,
)
from tools.utils.normalization import (
    DEFAULT_TIMEZONE,
    UTC,
    ClockDriftStatus,
    TimestampIssue,
    check_clock_drift,
    format_utc_timestamp,
    is_stale,
    normalize_timestamp,
    normalize_timestamp_column,
    normalize_timestamp_sequence,
    parse_datetime,
    to_naive_utc,
    to_utc_datetime,
    utc_now,
    validate_timestamp_sequence,
)
from tools.utils.paths import ensure_dir, ensure_parent_dir, normalize_path
from tools.utils.standard import (
    AlertDeduplicator,
    DataQualityIssue,
    ErrorEvent,
    StandardEnvelope,
    StandardResponse,
    build_data_quality_issue,
    build_error_event,
    build_metadata,
    canonical_json,
    circuit_open_response,
    error_response,
    get_execution_ms,
    is_official_tool_allowed,
    response_from_exception,
    stable_identifier,
    success_response,
    validate_metric_labels,
    validate_ohlcv_records,
    validate_standard_response,
)

# The following list defines the approved public names exported by the utils domain.
# Since individual modules will be implemented incrementally, this list serves
# as the source of truth for public API boundaries.
__all__ = [
    "APPROVED_ERROR_CODES",
    "DEFAULT_TIMEZONE",
    "DEFAULT_VERSION",
    "ID_PREFIXES",
    "UTC",
    "AlertDeduplicator",
    "ClockDriftStatus",
    "ConfigurationError",
    "DataError",
    "DataQualityIssue",
    "Error",
    "ErrorEvent",
    "ErrorPayload",
    "ExternalServiceError",
    "SecurityError",
    "StandardEnvelope",
    "StandardResponse",
    "TimestampIssue",
    "ValidationError",
    "build_data_quality_issue",
    "build_error_event",
    "build_metadata",
    "canonical_json",
    "check_clock_drift",
    "circuit_open_response",
    "clear_trace_context",
    "code_for_exception",
    "configure_logging",
    "details_for_exception",
    "ensure_dir",
    "ensure_parent_dir",
    "ensure_version",
    "error_name",
    "error_response",
    "exception_to_error_payload",
    "format_utc_timestamp",
    "generate_causation_id",
    "generate_correlation_id",
    "generate_event_id",
    "generate_id",
    "generate_idempotency_id",
    "generate_prefixed_id",
    "generate_request_id",
    "generate_workflow_id",
    "get_execution_ms",
    "get_logger",
    "is_official_tool_allowed",
    "is_stale",
    "logger",
    "message_for",
    "normalize_error_code",
    "normalize_path",
    "normalize_timestamp",
    "normalize_timestamp_column",
    "normalize_timestamp_sequence",
    "parse_datetime",
    "raise_for_invalid_code",
    "response_from_exception",
    "set_trace_context",
    "stable_identifier",
    "success_response",
    "to_naive_utc",
    "to_utc_datetime",
    "utc_now",
    "validate_error_payload",
    "validate_id",
    "validate_metric_labels",
    "validate_ohlcv_records",
    "validate_request_id",
    "validate_standard_response",
    "validate_timestamp_sequence",
    "validate_workflow_id",
]
